AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Catalogo AWS - Serverless Infrastructure

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs20.x
    Architectures:
      - arm64
    Environment:
      Variables:
        NODE_ENV: production
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
        PRODUCTS_TABLE: !Ref ProductsTable
        IMAGES_BUCKET: !Ref ImagesBucket
    Tracing: Active

Parameters:
  Environment:
    Type: String
    Default: production
  
  AdminEmail:
    Type: String
    Default: admin@example.com

Resources:
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-Products'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S
        - AttributeName: codice
          AttributeType: S
        - AttributeName: categoriaIt
          AttributeType: S
      KeySchema:
        - AttributeName: productId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CodiceIndex
          KeySchema:
            - AttributeName: codice
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: CategoryIndex
          KeySchema:
            - AttributeName: categoriaIt
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-images-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: ['*']
            AllowedMethods: [GET, PUT, POST, DELETE, HEAD]
            AllowedHeaders: ['*']
            MaxAge: 3600
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  ImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImagesBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${ImagesBucket.Arn}/*'

  ImagesCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt ImagesBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${AWS::StackName}-AdminPool'
      AutoVerifiedAttributes: [email]
      UsernameAttributes: [email]
      UsernameConfiguration:
        CaseSensitive: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      MfaConfiguration: OPTIONAL
      EnabledMfas: [SOFTWARE_TOKEN_MFA]
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${AWS::StackName}-AdminClient'
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30
      AccessTokenValidity: 60
      IdTokenValidity: 60
      TokenValidityUnits:
        RefreshToken: days
        AccessToken: minutes
        IdToken: minutes

  LambdaDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-Lambda-DLQ'
      MessageRetentionPeriod: 1209600

  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/apigateway/${AWS::StackName}'
      RetentionInDays: 30

  CatalogoApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub '${AWS::StackName}-API'
      StageName: !Ref Environment
      TracingEnabled: true
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn

  GetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-GetProducts'
      CodeUri: backend-lambda/
      Handler: src/handlers/public/getProducts.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogoApi
            Path: /api/public/catalogo/prodotti
            Method: GET
            Auth:
              Authorizer: NONE

  GetProductByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-GetProductById'
      CodeUri: backend-lambda/
      Handler: src/handlers/public/getProductById.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogoApi
            Path: /api/public/catalogo/prodotti/{productId}
            Method: GET
            Auth:
              Authorizer: NONE

  GetCategoriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-GetCategories'
      CodeUri: backend-lambda/
      Handler: src/handlers/public/getCategories.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogoApi
            Path: /api/public/catalogo/categorie
            Method: GET
            Auth:
              Authorizer: NONE

  GetProductsByCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-GetProductsByCategory'
      CodeUri: backend-lambda/
      Handler: src/handlers/public/getProductsByCategory.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        GetByCategory:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogoApi
            Path: /api/public/catalogo/categoria/{categoria}
            Method: GET
            Auth:
              Authorizer: NONE
        GetByCategoryAndSubcategory:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogoApi
            Path: /api/public/catalogo/categoria/{categoria}/sottocategoria/{sottocategoria}
            Method: GET
            Auth:
              Authorizer: NONE
        GetSubcategories:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogoApi
            Path: /api/public/catalogo/categoria/{categoria}/sottocategorie
            Method: GET
            Auth:
              Authorizer: NONE

  CreateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-CreateProduct'
      CodeUri: backend-lambda/
      Handler: src/handlers/admin/createProduct.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogoApi
            Path: /api/admin/prodotti
            Method: POST

  UpdateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-UpdateProduct'
      CodeUri: backend-lambda/
      Handler: src/handlers/admin/updateProduct.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogoApi
            Path: /api/admin/prodotti/{productId}
            Method: PUT

  DeleteProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-DeleteProduct'
      CodeUri: backend-lambda/
      Handler: src/handlers/admin/deleteProduct.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
        - S3CrudPolicy:
            BucketName: !Ref ImagesBucket
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogoApi
            Path: /api/admin/prodotti/{productId}
            Method: DELETE

  GetPresignedUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-GetPresignedUrl'
      CodeUri: backend-lambda/
      Handler: src/handlers/upload/getPresignedUrl.handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref ImagesBucket
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogoApi
            Path: /api/admin/upload/presigned-url
            Method: POST

Outputs:
  ApiEndpoint:
    Value: !Sub 'https://${CatalogoApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
  
  PublicApiBaseUrl:
    Value: !Sub 'https://${CatalogoApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/api/public/catalogo'
  
  AdminApiBaseUrl:
    Value: !Sub 'https://${CatalogoApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/api/admin'
  
  CognitoUserPoolId:
    Value: !Ref CognitoUserPool
  
  CognitoUserPoolClientId:
    Value: !Ref CognitoUserPoolClient
  
  ProductsTableName:
    Value: !Ref ProductsTable
  
  ImagesBucketName:
    Value: !Ref ImagesBucket
  
  CloudFrontDomain:
    Value: !GetAtt ImagesCloudFrontDistribution.DomainName
  
  Region:
    Value: !Ref AWS::Region