AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Catalogo AWS - Complete Serverless Infrastructure
  Backend Lambda + API Gateway + DynamoDB + S3 + Cognito
  Fault-tolerant with retry logic, DLQ, and monitoring

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        NODE_ENV: production
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
        PRODUCTS_TABLE: !Ref ProductsTable
        IMAGES_BUCKET: !Ref ImagesBucket
    Tracing: Active # X-Ray tracing enabled
    DeadLetterQueue:
      Type: SQS
      TargetArn: !GetAtt LambdaDeadLetterQueue.Arn

  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"
      MaxAge: "'600'"
    Auth:
      DefaultAuthorizer: CognitoAuthorizer
      AddDefaultAuthorizerToCorsPreflight: false
      Authorizers:
        CognitoAuthorizer:
          UserPoolArn: !GetAtt CognitoUserPool.Arn

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - staging
      - production
    Description: Environment name

  AdminEmail:
    Type: String
    Description: Email address for the admin user
    Default: admin@example.com

Resources:
  #############################################################################
  # DYNAMODB TABLES
  #############################################################################

  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-Products'
      BillingMode: PAY_PER_REQUEST # On-demand pricing for variable workloads
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true # Backup enabled
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES # Enable streams for triggers
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S
        - AttributeName: codice
          AttributeType: S
        - AttributeName: categoriaIt
          AttributeType: S
      KeySchema:
        - AttributeName: productId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CodiceIndex
          KeySchema:
            - AttributeName: codice
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: CategoryIndex
          KeySchema:
            - AttributeName: categoriaIt
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: Catalogo

  #############################################################################
  # S3 BUCKETS
  #############################################################################

  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-images-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled # Version control for files
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedHeaders:
              - '*'
            MaxAge: 3600
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: Catalogo

  ImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImagesBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${ImagesBucket.Arn}/*'

  #############################################################################
  # CLOUDFRONT CDN (for S3 images)
  #############################################################################

  ImagesCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'CDN for ${AWS::StackName} product images'
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Managed-CachingOptimized
          Compress: true
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt ImagesBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
        PriceClass: PriceClass_100 # Use only North America and Europe
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

  #############################################################################
  # COGNITO USER POOL
  #############################################################################

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${AWS::StackName}-AdminPool'
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      MfaConfiguration: OPTIONAL
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
      Tags:
        - Key: Environment
          Value: !Ref Environment

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${AWS::StackName}-AdminClient'
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30
      AccessTokenValidity: 60
      IdTokenValidity: 60
      TokenValidityUnits:
        RefreshToken: days
        AccessToken: minutes
        IdToken: minutes

  #############################################################################
  # SQS DEAD LETTER QUEUE
  #############################################################################

  LambdaDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-Lambda-DLQ'
      MessageRetentionPeriod: 1209600 # 14 days
      Tags:
        - Key: Environment
          Value: !Ref Environment

  #############################################################################
  # API GATEWAY
  #############################################################################

  CatalogoApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub '${AWS::StackName}-API'
      StageName: !Ref Environment
      TracingEnabled: true
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: '/*'
          HttpMethod: '*'
          MetricsEnabled: true
          DataTraceEnabled: true
          ThrottlingBurstLimit: 200
          ThrottlingRateLimit: 100
      AccessLogSetting:
        DestinationArn: !GetAtt ApiGatewayLogGroup.Arn
        Format: '$context.requestId $context.error.message $context.error.messageString'

  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/apigateway/${AWS::StackName}'
      RetentionInDays: 30

  #############################################################################
  # LAMBDA FUNCTIONS - PUBLIC (No Auth)
  #############################################################################

  GetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-GetProducts'
      CodeUri: backend-lambda/
      Handler: src/handlers/public/getProducts.handler
      Description: Get all products (public)
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        GetProducts:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogoApi
            Path: /api/public/catalogo/prodotti
            Method: GET
            Auth:
              Authorizer: NONE

  GetProductByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-GetProductById'
      CodeUri: backend-lambda/
      Handler: src/handlers/public/getProductById.handler
      Description: Get product by ID (public)
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        GetProductById:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogoApi
            Path: /api/public/catalogo/prodotti/{productId}
            Method: GET
            Auth:
              Authorizer: NONE

  GetCategoriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-GetCategories'
      CodeUri: backend-lambda/
      Handler: src/handlers/public/getCategories.handler
      Description: Get all categories (public)
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        GetCategories:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogoApi
            Path: /api/public/catalogo/categorie
            Method: GET
            Auth:
              Authorizer: NONE

  GetProductsByCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-GetProductsByCategory'
      CodeUri: backend-lambda/
      Handler: src/handlers/public/getProductsByCategory.handler
      Description: Get products by category/subcategory (public)
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ProductsTable
      Events:
        GetByCategory:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogoApi
            Path: /api/public/catalogo/categoria/{categoria}
            Method: GET
            Auth:
              Authorizer: NONE
        GetByCategoryAndSubcategory:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogoApi
            Path: /api/public/catalogo/categoria/{categoria}/sottocategoria/{sottocategoria}
            Method: GET
            Auth:
              Authorizer: NONE
        GetSubcategories:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogoApi
            Path: /api/public/catalogo/categoria/{categoria}/sottocategorie
            Method: GET
            Auth:
              Authorizer: NONE

  #############################################################################
  # LAMBDA FUNCTIONS - ADMIN (Cognito Auth Required)
  #############################################################################

  CreateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-CreateProduct'
      CodeUri: backend-lambda/
      Handler: src/handlers/admin/createProduct.handler
      Description: Create new product (admin only)
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Events:
        CreateProduct:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogoApi
            Path: /api/admin/prodotti
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  UpdateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-UpdateProduct'
      CodeUri: backend-lambda/
      Handler: src/handlers/admin/updateProduct.handler
      Description: Update product (admin only)
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Events:
        UpdateProduct:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogoApi
            Path: /api/admin/prodotti/{productId}
            Method: PUT
            Auth:
              Authorizer: CognitoAuthorizer

  DeleteProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-DeleteProduct'
      CodeUri: backend-lambda/
      Handler: src/handlers/admin/deleteProduct.handler
      Description: Delete product (admin only)
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
        - S3CrudPolicy:
            BucketName: !Ref ImagesBucket
      Events:
        DeleteProduct:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogoApi
            Path: /api/admin/prodotti/{productId}
            Method: DELETE
            Auth:
              Authorizer: CognitoAuthorizer

  GetPresignedUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-GetPresignedUrl'
      CodeUri: backend-lambda/
      Handler: src/handlers/upload/getPresignedUrl.handler
      Description: Generate presigned URL for image upload (admin only)
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref ImagesBucket
      Events:
        GetPresignedUrl:
          Type: Api
          Properties:
            RestApiId: !Ref CatalogoApi
            Path: /api/admin/upload/presigned-url
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  #############################################################################
  # CLOUDWATCH ALARMS
  #############################################################################

  ApiGateway4xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-API-4xx-Errors'
      AlarmDescription: Alert when API Gateway 4xx errors exceed threshold
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 50
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub '${AWS::StackName}-API'

  ApiGateway5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-API-5xx-Errors'
      AlarmDescription: Alert when API Gateway 5xx errors exceed threshold
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Sub '${AWS::StackName}-API'

  DynamoDBThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-DynamoDB-Throttle'
      AlarmDescription: Alert when DynamoDB throttles requests
      MetricName: UserErrors
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: TableName
          Value: !Ref ProductsTable

#############################################################################
# OUTPUTS
#############################################################################

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${CatalogoApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${AWS::StackName}-ApiEndpoint'

  PublicApiBaseUrl:
    Description: Public API base URL (for frontend-catalogo-utente)
    Value: !Sub 'https://${CatalogoApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/api/public/catalogo'
    Export:
      Name: !Sub '${AWS::StackName}-PublicApiBaseUrl'

  AdminApiBaseUrl:
    Description: Admin API base URL (for frontend-catalogo-admin)
    Value: !Sub 'https://${CatalogoApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/api/admin'
    Export:
      Name: !Sub '${AWS::StackName}-AdminApiBaseUrl'

  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool
    Export:
      Name: !Sub '${AWS::StackName}-CognitoUserPoolId'

  CognitoUserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref CognitoUserPoolClient
    Export:
      Name: !Sub '${AWS::StackName}-CognitoUserPoolClientId'

  CognitoUserPoolArn:
    Description: Cognito User Pool ARN
    Value: !GetAtt CognitoUserPool.Arn
    Export:
      Name: !Sub '${AWS::StackName}-CognitoUserPoolArn'

  ProductsTableName:
    Description: DynamoDB Products Table Name
    Value: !Ref ProductsTable
    Export:
      Name: !Sub '${AWS::StackName}-ProductsTableName'

  ImagesBucketName:
    Description: S3 Images Bucket Name
    Value: !Ref ImagesBucket
    Export:
      Name: !Sub '${AWS::StackName}-ImagesBucketName'

  ImagesBucketUrl:
    Description: S3 Images Bucket URL
    Value: !GetAtt ImagesBucket.WebsiteURL
    Export:
      Name: !Sub '${AWS::StackName}-ImagesBucketUrl'

  CloudFrontDistributionDomain:
    Description: CloudFront distribution domain for images
    Value: !GetAtt ImagesCloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDomain'

  DeadLetterQueueUrl:
    Description: SQS Dead Letter Queue URL
    Value: !Ref LambdaDeadLetterQueue
    Export:
      Name: !Sub '${AWS::StackName}-DLQUrl'

  Region:
    Description: AWS Region
    Value: !Ref AWS::Region
    Export:
      Name: !Sub '${AWS::StackName}-Region'
